import * as React from 'react';
import TextField from '@mui/material/TextField';
import Stack from '@mui/material/Stack';
import Autocomplete from '@mui/material/Autocomplete';

export default function FreeSolo({ value, setValue }) {
  return (
    <Autocomplete
      id="free-solo-demo species-select-1"
      freeSolo
      value={value}
      options={species.map((option) => option)}
      onInputChange={(e, newInputValue) => setValue(newInputValue)}
      renderInput={(params) => <TextField {...params} label="Bird Specie" />}
    />
  );
}

// ----------------------------------------------------------------------------------------------------------------------------
const species = [
  'ABBOTTS BABBLER',
  'MASKED BOOBY',
  'ABBOTTS BOOBY',
  'HORNBILL',
  'MALABAR HORNBILL',
  'ABYSSINIAN GROUND HORNBILL',
  'AFRICAN CROWNED CRANE',
  'DEMOISELLE CRANE',
  'SANDHILL CRANE',
  'COMMON HOUSE MARTIN',
  'PURPLE MARTIN',
  'SAND MARTIN',
  'SATYR TRAGOPAN',
  'SAMATRAN THRUSH',
  'VARIED THRUSH',
  'ASHY THRUSHBIRD',
  'CAPE ROCK THRUSH',
  'RED TAILED THRUSH',
  'CRANE HAWK',
  'RED TAILED HAWK',
  'NORTHERN GOSHAWK',
  'NORTHERN JACANA',
  'NORTHERN GANNET',
  'NORTHERN FULMAR',
  'NORTHERN FLICKER',
  'GILDED FLICKER',
  'GILA WOODPECKER',
  'RED HEADED WOODPECKER',
  'BLONDE CRESTED WOODPECKER',
  'CREAM COLORED WOODPECKER',
  'DOWNY WOODPECKER',
  'DARK EYED JUNCO',
  'DOUBLE BARRED FINCH',
  'EUROPEAN GOLDFINCH',
  'GOULDIAN FINCH',
  'HAWFINCH',
  'HOUSE FINCH',
  'PATAGONIAN SIERRA FINCH',
  'PURPLE FINCH',
  'RED BROWED FINCH',
  'STRAWBERRY FINCH',
  'AFRICAN FIREFINCH',
  'AMERICAN GOLDFINCH',
  'OYSTER CATCHER',
  'AFRICAN OYSTER CATCHER',
  'VERMILION FLYCATCHER',
  'ROYAL FLYCATCHER',
  'CINNAMON FLYCATCHER',
  'ALBATROSS',
  'ALBERTS TOWHEE',
  'JANDAYA PARAKEET',
  'ALEXANDRINE PARAKEET',
  'ALPINE CHOUGH',
  'ALTAMIRA YELLOWTHROAT',
  'AMERICAN AVOCET',
  'MANGROVE CUCKOO',
  'AFRICAN EMERALD CUCKOO',
  'AMERICAN BITTERN',
  'AMERICAN COOT',
  'AMERICAN KESTREL',
  'GOLDEN PIPIT',
  'AMERICAN PIPIT',
  'AMERICAN REDSTART',
  'AMETHYST WOODSTAR',
  'HAWAIIAN GOOSE',
  'MAGPIE GOOSE',
  'ANDEAN GOOSE',
  'MASKED LAPWING',
  'WATTLED LAPWING',
  'ANDEAN LAPWING',
  'ANDEAN SISKIN',
  'ANHINGA',
  'ANIANIAU',
  'RUBY THROATED HUMMINGBIRD',
  'ANNAS HUMMINGBIRD',
  'ANTBIRD',
  'CHESTNET BELLIED EUPHONIA',
  'ANTILLEAN EUPHONIA',
  'APAPANE',
  'APOSTLEBIRD',
  'STRIPPED MANAKIN',
  'ARARIPE MANAKIN',
  'ASIAN CRESTED IBIS',
  'BALD IBIS',
  'GLOSSY IBIS',
  'SCARLET IBIS',
  'HOUSE SPARROW',
  'JAVA SPARROW',
  'BLACK-THROATED SPARROW',
  'CHIPPING SPARROW',
  'CINNAMON ATTILA',
  'GRAY PARTRIDGE',
  'CHINESE BAMBOO PARTRIDGE',
  'CHUKAR PARTRIDGE',
  'CHUCAO TAPACULO',
  'BLUE HERON',
  'CAPPED HERON',
  'CHINESE POND HERON',
  'AVADAVAT',
  'AZURE JAY',
  'GREEN JAY',
  'GRAY CATBIRD',
  'SPOTTED CATBIRD',
  'SRI LANKA BLUE MAGPIE',
  'TAIWAN MAGPIE',
  'EURASIAN MAGPIE',
  'GREEN MAGPIE',
  'IBERIAN MAGPIE',
  'MALLARD DUCK',
  'MANDRIN DUCK',
  'RED HEADED DUCK',
  'STEAMER DUCK',
  'TEAL DUCK',
  'WOOD DUCK',
  'HARLEQUIN DUCK',
  'MALACHITE KINGFISHER',
  'PYGMY KINGFISHER',
  'RUDY KINGFISHER',
  'RUFOUS KINGFISHER',
  'STORK BILLED KINGFISHER',
  'BELTED KINGFISHER',
  'CRESTED KINGFISHER',
  'GREAT GRAY OWL',
  'LONG-EARED OWL',
  'ORIENTAL BAY OWL',
  'SNOWY OWL',
  'STRIPED OWL',
  'BARN OWL',
  'BARN SWALLOW',
  'STRIPPED SWALLOW',
  'TREE SWALLOW',
  'VIOLET GREEN SWALLOW',
  'BLACK TAIL CRAKE',
  'WHITE BROWED CRAKE',
  'VENEZUELIAN TROUPIAL',
  'VICTORIA CROWNED PIGEON',
  'CROWNED PIGEON',
  'NICOBAR PIGEON',
  'VULTURINE GUINEAFOWL',
  'GUINEAFOWL',
  'RED HONEY CREEPER',
  'WALL CREEPER',
  'BROWN CREEPER',
  'WATTLED CURASSOW',
  'WHITE CHEEKED TURACO',
  'GUINEA TURACO',
  'VIOLET TURACO',
  'WHITE NECKED RAVEN',
  'WHITE TAILED TROPIC',
  'BUSH TURKEY',
  'OCELLATED TURKEY',
  'WILD TURKEY',
  'YELLOW BELLIED FLOWERPECKER',
  'YELLOW CACIQUE',
  'YELLOW HEADED BLACKBIRD',
  'RED WINGED BLACKBIRD',
  'TURQUOISE MOTMOT',
  'RUFUOS MOTMOT',
  'TURKEY VULTURE',
  'BLACK VULTURE',
  'KING VULTURE',
  'TRUMPTER SWAN',
  'BLACK SWAN',
  'TROPICAL KINGBIRD',
  'GRAY KINGBIRD',
  'TASMANIAN HEN',
  'SUPERB STARLING',
  'BALI STARLING',
  'CAPE GLOSSY STARLING',
  'COMMON STARLING',
  'EMERALD TANAGER',
  'FLAME TANAGER',
  'HEPATIC TANAGER',
  'PARADISE TANAGER',
  'SCARLET TANAGER',
  'AZURE TANAGER',
  'AZURE TIT',
  'BLACK THROATED BUSHTIT',
  'CRESTED SHRIKETIT',
  'BAIKAL TEAL',
  'CINNAMON TEAL',
  'GOLDEN EAGLE',
  'HARPY EAGLE',
  'PHILIPPINE EAGLE',
  'BALD EAGLE',
  'BALTIMORE ORIOLE',
  'EURASIAN GOLDEN ORIOLE',
  'HORNED GUAN',
  'BAND TAILED GUAN',
  'BANDED BROADBILL',
  'BLACK & YELLOW BROADBILL',
  'GREEN BROADBILL',
  'BANDED PITA',
  'EARED PITA',
  'BANDED STILT',
  'BAR-TAILED GODWIT',
  'BARRED PUFFBIRD',
  'BARROWS GOLDENEYE',
  'BAY-BREASTED WARBLER',
  'BLACK THROATED WARBLER',
  'BLACKBURNIAM WARBLER',
  'CAPE MAY WARBLER',
  'CERULEAN WARBLER',
  'GOLD WING WARBLER',
  'GOLDEN CHEEKED WARBLER',
  'RED FACED WARBLER',
  'TOWNSENDS WARBLER',
  'BEARDED BARBET',
  'D-ARNAUDS BARBET',
  'BEARDED BELLBIRD',
  'BEARDED REEDLING',
  'BLACK BAZA',
  'BLACK COCKATOO',
  'COCKATOO',
  'GANG GANG COCKATOO',
  'BLACK FRANCOLIN',
  'BLACK SKIMMER',
  'BLACK-CAPPED CHICKADEE',
  'CAPUCHINBIRD',
  'BLACK-NECKED GREBE',
  'BLUE COAU',
  'BLUE GROUSE',
  'GREATOR SAGE GROUSE',
  'BLUE THROATED TOUCANET',
  'BORNEAN LEAFBIRD',
  'ELLIOTS  PHEASANT',
  'MIKADO  PHEASANT',
  'RING-NECKED PHEASANT',
  'SWINHOES PHEASANT',
  'BORNEAN PHEASANT',
  'BULWERS PHEASANT',
  'GOLDEN PHEASANT',
  'BRANDT CORMARANT',
  'DOUBLE BRESTED CORMARANT',
  'BROWN NODDY',
  'BORNEAN BRISTLEHEAD',
  'BROWN THRASHER',
  'CACTUS WREN',
  'SPLENDID WREN',
  'CALIFORNIA CONDOR',
  'CALIFORNIA GULL',
  'IVORY GULL',
  'CALIFORNIA QUAIL',
  'GAMBELS QUAIL',
  'HARLEQUIN QUAIL',
  'RED BEARDED BEE EATER',
  'WHITE THROATED BEE EATER',
  'CARMINE BEE-EATER',
  'CASPIAN TERN',
  'FAIRY TERN',
  'INCA TERN',
  'CEDAR WAXWING',
  'DUSKY LORY',
  'CHATTERING LORY',
  'CLARKS NUTCRACKER',
  'COLLARED ARACARI',
  'CURL CRESTED ARACARI',
  'COMMON FIRECREST',
  'COMMON GRACKLE',
  'COMMON IORA',
  'COMMON LOON',
  'COMMON POORWILL',
  'COPPERY TAILED COUCAL',
  'CRAB PLOVER',
  'GREY PLOVER',
  'CRESTED CARACARA',
  'CRESTED NUTHATCH',
  'CRESTED OROPENDOLA',
  'CRIMSON SUNBIRD',
  'CUBAN TODY',
  'COCK OF THE  ROCK',
  'CRESTED AUKLET',
  'PARAKETT AUKLET',
  'CAPE LONGCLAW',
  'CRESTED COUA',
  'CRESTED FIREBACK',
  'CRIMSON CHAT',
  'CROW',
  'CUBAN TROGON',
  'ELEGANT TROGON',
  'RED NAPED TROGON',
  'DOUBLE EYED FIG PARROT',
  'EASTERN BLUEBIRD',
  'FAIRY BLUEBIRD',
  'EASTERN GOLDEN WEAVER',
  'EASTERN ROSELLA',
  'EASTERN TOWEE',
  'EMPEROR PENGUIN',
  'FIORDLAND PENGUIN',
  'MYNA',
  'ENGGANO MYNA',
  'EUROPEAN TURTLE DOVE',
  'MOURNING DOVE',
  'ROCK DOVE',
  'SCARLET CROWNED FRUIT DOVE',
  'EVENING GROSBEAK',
  'FIRE TAILLED MYZORNIS',
  'FLAME BOWERBIRD',
  'REGENT BOWERBIRD',
  'GOLDEN CHLOROPHONIA',
  'GROVED BILLED ANI',
  'GURNEYS PITTA',
  'INDIAN PITTA',
  'RED BELLIED PITTA',
  'HIMALAYAN BLUETAIL',
  'HIMALAYAN MONAL',
  'HORNED LARK',
  'HYACINTH MACAW',
  'SCARLET MACAW',
  'IMPERIAL SHAQ',
  'CANARY',
  'CASSOWARY',
  'EMU',
  'FLAMINGO',
  'FRIGATE',
  'GO AWAY BIRD',
  'GYRFALCON',
  'PEREGRINE FALCON',
  'HAMMERKOP',
  'HELMET VANGA',
  'HOODED MERGANSER',
  'HORNED SUNGEM',
  'INDIAN BUSTARD',
  'INDIAN ROLLER',
  'LILAC ROLLER',
  'LAZULI BUNTING',
  'LARK BUNTING',
  'ORANGE BRESTED BUNTING',
  'PAINTED BUNTING',
  'INDIGO BUNTING',
  'INLAND DOTTEREL',
  'JACK SNIPE',
  'JAPANESE ROBIN',
  'PINK ROBIN',
  'ROBIN',
  'LITTLE AUK',
  'MARABOU STORK',
  'NOISY FRIARBIRD',
  'NORTHERN CARDINAL',
  'NORTHERN MOCKINGBIRD',
  'NORTHERN PARULA',
  'NORTHERN RED BISHOP',
  'NORTHERN SHOVELER',
  'OKINAWA RAIL',
  'TIT MOUSE',
  'SPOON BILED SANDPIPER',
  'SPANGLED COTINGA',
  'SNOWY EGRET',
  'SMITHS LONGSPUR',
  'SHORT BILLED DOWITCHER',
  'ROUGH LEG BUZZARD',
  'ROSY FACED LOVEBIRD',
  'RED WISKERED BULBUL',
  'RED FACED CORMORANT',
  'RAINBOW LORIKEET',
  'PURPLE SWAMPHEN',
  'PURPLE GALLINULE',
  'POMARINE JAEGER',
  'LESSER ADJUTANT',
  'GREAT POTOO',
  'GREAT KISKADEE',
  'GREAT JACAMAR',
  'BANANAQUIT',
  'BIRD OF PARADISE',
  'BOBOLINK',
  'CHARA DE COLLAR',
  'EASTERN MEADOWLARK',
  'HOATZIN',
  'HOOPOES',
  'IBISBILL',
  'IWI',
  'JABIRU',
  'KAGU',
  'KAKAPO',
  'KILLDEAR',
  'KIWI',
  'KOOKABURRA',
  'MALAGASY WHITE EYE',
  'MALEO',
  'OSPREY',
  'OSTRICH',
  'OVENBIRD',
  'PALILA',
  'PEACOCK',
  'PELICAN',
  'PUFFIN',
  'QUETZAL',
  'RAZORBILL',
  'PARUS MAJOR',
  'RED FODY',
  'ROADRUNNER',
  'SHOEBILL',
  'SORA',
  'SPOONBILL',
  'TAILORBIRD',
  'TAKAHE',
  'UMBRELLA BIRD',
  'WHIMBREL',
  'WILSONS BIRD OF PARADISE',
  'TOUCHAN',
];

// -----------------------------------------------------------------------------------------------------------------------------

const birds = [
  'Babbler',
  'Booby',
  'Hornbill',
  'Crane',
  'Martin',
  'Tragopan',
  'Hawk',
  'Jacana',
  'Gannet',
  'Fulmar',
  'Flicker',
  'Woodpecker',
  'Junco',
  'Finch',
  'Catcher',
  'Flycatcher',
  'Albatross',
  'Towhee',
  'Parakeet',
  'Chough',
  'Yellowthroat',
  'Avocet',
  'Cuckoo',
  'Bittern',
  'Coot',
  'Kestrel',
  'Pipit',
  'Redstart',
  'Woodstart',
  'Goose',
  'Lapwing',
  'Siskin',
  'Anhinga',
  'Anianiau',
  'Hummingbird',
  'Antbird',
  'Euphonia',
  'Apapane',
  'Apostlebird',
  'Manakin',
  'Ibis',
  'Sparrow',
  'Attila',
  'Patridge',
  'Tapaculo',
  'Heron',
  'Avadat',
  'Jay',
  'Catbird',
  'Magpie',
  'Duck',
  'Kingfisher',
  'Owl',
  'Swallow',
  'Crake',
  'Troupial',
  'Pigeon',
  'GuineaFowl',
  'Creeper',
  'Curassow',
  'Turaco',
  'Raven',
  'Tropic',
  'Turkey',
  'FlowerPecker',
  'Cacique',
  'Backbird',
  'Motmot',
  'Vulture',
  'Swan',
  'Kingbird',
  'Hen',
  'Starling',
  'Tanager',
  'Tit',
  'Teal',
  'Eagle',
  'Oriole',
  'Guan',
  'Broadbill',
  'Pita',
  'Stilt',
  'Godwit',
  'Puffbird',
  'Goldeneye',
  'Warbler',
  'Barbet',
  'Bellbird',
  'Reedling',
  'Baza',
  'Cockatoo',
  'Francolin',
  'Skimmer',
  'Chickadee',
  'Grebe',
  'Coau',
  'Grouse',
  'Toucanet',
  'Leafbird',
  'Pheasant',
  'Cormarant',
  'Noddy',
  'Bristlehead',
  'Thrasher',
  'Wren',
  'Condor',
  'Gull',
  'Quail',
  'BeeEater',
  'Tern',
  'Waxwing',
  'Lory',
  'Nutcracker',
  'Aracari',
  'Firecrest',
  'Grackle',
  'Iora',
  'Loon',
  'Poorwill',
  'Coucal',
  'Plover',
  'Caracara',
  'Nuthatch',
  'Oropendola',
  'Sunbird',
  'Tody',
  'Cock',
  'Auklet',
  'Longclaw',
  'Coua',
  'Fireback',
  'Chat',
  'Crow',
  'Trogon',
  'Parrot',
  'Bluebird',
  'Weaver',
  'Rosella',
  'Towee',
  'Penguin',
  'Myna',
  'Dove',
  'Grosbeak',
  'Myzornis',
  'Bowerbird',
  'Chlorophonia',
  'Ani',
  'Pitta',
  'Bluetail',
  'Monal',
  'Lark',
  'Macaw',
  'Shaq',
  'Canary',
  'Casswary',
  'Emu',
  'Flamingo',
  'Frigate',
  'GoAwayBird',
  'Falcon',
  'Hammerkop',
  'Vanga',
  'Merganser',
  'Sungem',
  'Bustard',
  'Roller',
  'Bunting',
  'Dotterel',
  'Snipe',
  'Robin',
  'Auk',
  'Stork',
  'Friarbird',
  'Cardinal',
  'Mockingbird',
  'Parula',
  'Bishop',
  'Shoveler',
  'Rail',
  'TitMouse',
  'Sandpiper',
  'Cotinga',
  'Egret',
  'Longspur',
  'Dowitcher',
  'Buzzard',
  'Lovebird',
  'Bulbul',
  'Cormorant',
  'Lorikeet',
  'Swamphen',
  'Gallinule',
  'Jaeger',
  'Adjutant',
  'Potoo',
  'Kiskadee',
  'Jacamar',
  'Bananaquit',
  'BirdOfParadise',
  'Bobolink',
  'CharaDeCollar',
  'Meadowlark',
  'Hoatzin',
  'Hoopoes',
  'Ibisbill',
  'Iwi',
  'Jabiru',
  'Kagu',
  'Kakapo',
  'Killdear',
  'Kiwi',
  'Kookaburra',
  'Malagasy',
  'Maleo',
  'Osprey',
  'Ostritch',
  'Ovenbird',
  'Palila',
  'Peacock',
  'Pelican',
  'Puffin',
  'Quetzal',
  'Razorbill',
  'Parus',
  'Fody',
  'RoadRunner',
  'ShoeBill',
  'Sora',
  'Spoonbill',
  'Tailorbird',
  'Takahe',
  'Umbrellabird',
  'Whimbrel',
  'Wilsons',
  'Touchan',
];

// ----------------------------------------------------------------------------------------------

const classifiedSpecies = [
  { Babbler: ['ABBOTTS BABBLER'] },
  { Booby: ['MASKED BOOBY', 'ABBOTTS BOOBY'] },
  { Hornbill: ['HORNBILL', 'MALABAR HORNBILL', 'ABYSSINIAN GROUND HORNBILL'] },
  { Crane: ['AFRICAN CROWNED CRANE', 'DEMOISELLE CRANE', 'SANDHILL CRANE'] },
  { Martin: ['COMMON HOUSE MARTIN', 'PURPLE MARTIN', 'SAND MARTIN'] },
  { Tragopan: ['SATYR TRAGOPAN'] },
  {
    Thrush: [
      'SAMATRAN THRUSH',
      'VARIED THRUSH',
      'ASHY THRUSHBIRD',
      'CAPE ROCK THRUSH',
      'RED TAILED THRUSH',
    ],
  },
  { Hawk: ['CRANE HAWK', 'RED TAILED HAWK', 'NORTHERN GOSHAWK'] },
  { Jacana: ['NORTHERN JACANA'] },
  { Gannet: ['NORTHERN GANNET'] },
  { Fulmar: ['NORTHERN FULMAR'] },
  { Flicker: ['NORTHERN FLICKER', 'GILDED FLICKER'] },
  {
    Woodpecker: [
      'GILA WOODPECKER',
      'RED HEADED WOODPECKER',
      'BLONDE CRESTED WOODPECKER',
      'CREAM COLORED WOODPECKER',
      'DOWNY WOODPECKER',
    ],
  },
  { Junco: ['DARK EYED JUNCO'] },
  {
    Finch: [
      'DOUBLE BARRED FINCH',
      'EUROPEAN GOLDFINCH',
      'GOULDIAN FINCH',
      'HAWFINCH',
      'HOUSE FINCH',
      'PATAGONIAN SIERRA FINCH',
      'PURPLE FINCH',
      'RED BROWED FINCH',
      'STRAWBERRY FINCH',
      'AFRICAN FIREFINCH',
      'AMERICAN GOLDFINCH',
    ],
  },
  { Catcher: ['OYSTER CATCHER', 'AFRICAN OYSTER CATCHER'] },
  {
    Flycatcher: [
      'VERMILION FLYCATCHER',
      'ROYAL FLYCATCHER',
      'CINNAMON FLYCATCHER',
    ],
  },
  { Albatross: ['ALBATROSS'] },
  { Towhee: ['ALBERTS TOWHEE'] },
  { Parakeet: ['JANDAYA PARAKEET', 'ALEXANDRINE PARAKEET'] },
  { Chough: ['ALPINE CHOUGH'] },
  { Yellowthroat: ['ALTAMIRA YELLOWTHROAT'] },
  { Avocet: ['AMERICAN AVOCET'] },
  { Cuckoo: ['MANGROVE CUCKOO', 'AFRICAN EMERALD CUCKOO'] },
  { Bittern: ['AMERICAN BITTERN'] },
  { Coot: ['AMERICAN COOT'] },
  { Kestrel: ['AMERICAN KESTREL'] },
  { Pipit: ['GOLDEN PIPIT', 'AMERICAN PIPIT'] },
  { Redstart: ['AMERICAN REDSTART'] },
  { Woodstart: ['AMETHYST WOODSTAR'] },
  { Goose: ['HAWAIIAN GOOSE', 'MAGPIE GOOSE', 'ANDEAN GOOSE'] },
  { Lapwing: ['MASKED LAPWING', 'WATTLED LAPWING', 'ANDEAN LAPWING'] },
  { Siskin: ['ANDEAN SISKIN'] },
  { Anhinga: ['ANHINGA'] },
  { Anianiau: ['ANIANIAU'] },
  { Hummingbird: ['RUBY THROATED HUMMINGBIRD', 'ANNAS HUMMINGBIRD'] },
  { Antbird: ['ANTBIRD'] },
  { Euphonia: ['CHESTNET BELLIED EUPHONIA', 'ANTILLEAN EUPHONIA'] },
  { Apapane: ['APAPANE'] },
  { Apostlebird: ['APOSTLEBIRD'] },
  { Manakin: ['STRIPPED MANAKIN', 'ARARIPE MANAKIN'] },
  { Ibis: ['ASIAN CRESTED IBIS', 'BALD IBIS', 'GLOSSY IBIS', 'SCARLET IBIS'] },
  {
    Sparrow: [
      'HOUSE SPARROW',
      'JAVA SPARROW',
      'BLACK-THROATED SPARROW',
      'CHIPPING SPARROW',
    ],
  },
  { Attila: ['CINNAMON ATTILA'] },
  {
    Patridge: [
      'GRAY PARTRIDGE',
      'CHINESE BAMBOO PARTRIDGE',
      'CHUKAR PARTRIDGE',
    ],
  },
  { Tapaculo: ['CHUCAO TAPACULO'] },
  { Heron: ['BLUE HERON', 'CAPPED HERON', 'CHINESE POND HERON'] },
  { Avadat: ['AVADAVAT'] },
  { Jay: ['AZURE JAY', 'GREEN JAY'] },
  { Catbird: ['GRAY CATBIRD', 'SPOTTED CATBIRD'] },
  {
    Magpie: [
      'SRI LANKA BLUE MAGPIE',
      'TAIWAN MAGPIE',
      'EURASIAN MAGPIE',
      'GREEN MAGPIE',
      'IBERIAN MAGPIE',
    ],
  },
  {
    Duck: [
      'MALLARD DUCK',
      'MANDRIN DUCK',
      'RED HEADED DUCK',
      'STEAMER DUCK',
      'TEAL DUCK',
      'WOOD DUCK',
      'HARLEQUIN DUCK',
    ],
  },
  {
    Kingfisher: [
      'MALACHITE KINGFISHER',
      'PYGMY KINGFISHER',
      'RUDY KINGFISHER',
      'RUFOUS KINGFISHER',
      'STORK BILLED KINGFISHER',
      'BELTED KINGFISHER',
      'CRESTED KINGFISHER',
    ],
  },
  {
    Owl: [
      'GREAT GRAY OWL',
      'LONG-EARED OWL',
      'ORIENTAL BAY OWL',
      'SNOWY OWL',
      'STRIPED OWL',
      'BARN OWL',
    ],
  },
  {
    Swallow: [
      'BARN SWALLOW',
      'STRIPPED SWALLOW',
      'TREE SWALLOW',
      'VIOLET GREEN SWALLOW',
    ],
  },
  { Crake: ['BLACK TAIL CRAKE', 'WHITE BROWED CRAKE'] },
  { Troupial: ['VENEZUELIAN TROUPIAL'] },
  { Pigeon: ['VICTORIA CROWNED PIGEON', 'CROWNED PIGEON', 'NICOBAR PIGEON'] },
  { GuineaFowl: ['VULTURINE GUINEAFOWL', 'GUINEAFOWL'] },
  { Creeper: ['RED HONEY CREEPER', 'WALL CREEPER', 'BROWN CREEPER'] },
  { Curassow: ['WATTLED CURASSOW'] },
  { Turaco: ['WHITE CHEEKED TURACO', 'GUINEA TURACO', 'VIOLET TURACO'] },
  { Raven: ['WHITE NECKED RAVEN'] },
  { Tropic: ['WHITE TAILED TROPIC'] },
  { Turkey: ['BUSH TURKEY', 'OCELLATED TURKEY', 'WILD TURKEY'] },
  { FlowerPecker: ['YELLOW BELLIED FLOWERPECKER'] },
  { Cacique: ['YELLOW CACIQUE'] },
  { Backbird: ['YELLOW HEADED BLACKBIRD', 'RED WINGED BLACKBIRD'] },
  { Motmot: ['TURQUOISE MOTMOT', 'RUFUOS MOTMOT'] },
  { Vulture: ['TURKEY VULTURE', 'BLACK VULTURE', 'KING VULTURE'] },
  { Swan: ['TRUMPTER SWAN', 'BLACK SWAN'] },
  { Kingbird: ['TROPICAL KINGBIRD', 'GRAY KINGBIRD'] },
  { Hen: ['TASMANIAN HEN'] },
  {
    Starling: [
      'SUPERB STARLING',
      'BALI STARLING',
      'CAPE GLOSSY STARLING',
      'COMMON STARLING',
    ],
  },
  {
    Tanager: [
      'EMERALD TANAGER',
      'FLAME TANAGER',
      'HEPATIC TANAGER',
      'PARADISE TANAGER',
      'SCARLET TANAGER',
      'AZURE TANAGER',
    ],
  },
  { Tit: ['AZURE TIT', 'BLACK THROATED BUSHTIT', 'CRESTED SHRIKETIT'] },
  { Teal: ['BAIKAL TEAL', 'CINNAMON TEAL'] },
  { Eagle: ['GOLDEN EAGLE', 'HARPY EAGLE', 'PHILIPPINE EAGLE', 'BALD EAGLE'] },
  { Oriole: ['BALTIMORE ORIOLE', 'EURASIAN GOLDEN ORIOLE'] },
  { Guan: ['HORNED GUAN', 'BAND TAILED GUAN'] },
  {
    Broadbill: [
      'BANDED BROADBILL',
      'BLACK & YELLOW BROADBILL',
      'GREEN BROADBILL',
    ],
  },
  { Pita: ['BANDED PITA', 'EARED PITA'] },
  { Stilt: ['BANDED STILT'] },
  { Godwit: ['BAR-TAILED GODWIT'] },
  { Puffbird: ['BARRED PUFFBIRD'] },
  { Goldeneye: ['BARROWS GOLDENEYE'] },
  {
    Warbler: [
      'BAY-BREASTED WARBLER',
      'BLACK THROATED WARBLER',
      'BLACKBURNIAM WARBLER',
      'CAPE MAY WARBLER',
      'CERULEAN WARBLER',
      'GOLD WING WARBLER',
      'GOLDEN CHEEKED WARBLER',
      'RED FACED WARBLER',
      'TOWNSENDS WARBLER',
    ],
  },
  { Barbet: ['BEARDED BARBET', 'D-ARNAUDS BARBET'] },
  { Bellbird: ['BEARDED BELLBIRD'] },
  { Reedling: ['BEARDED REEDLING'] },
  { Baza: ['BLACK BAZA'] },
  { Cockatoo: ['BLACK COCKATOO', 'COCKATOO', 'GANG GANG COCKATOO'] },
  { Francolin: ['BLACK FRANCOLIN'] },
  { Skimmer: ['BLACK SKIMMER'] },
  { Chickadee: ['BLACK-CAPPED CHICKADEE', 'CAPUCHINBIRD'] },
  { Grebe: ['BLACK-NECKED GREBE'] },
  { Coau: ['BLUE COAU'] },
  { Grouse: ['BLUE GROUSE', 'GREATOR SAGE GROUSE'] },
  { Toucanet: ['BLUE THROATED TOUCANET'] },
  { Leafbird: ['BORNEAN LEAFBIRD'] },
  {
    Pheasant: [
      'ELLIOTS  PHEASANT',
      'MIKADO  PHEASANT',
      'RING-NECKED PHEASANT',
      'SWINHOES PHEASANT',
      'BORNEAN PHEASANT',
      'BULWERS PHEASANT',
      'GOLDEN PHEASANT',
    ],
  },
  { Cormarant: ['BRANDT CORMARANT', 'DOUBLE BRESTED CORMARANT'] },
  { Noddy: ['BROWN NODDY'] },
  { Bristlehead: ['BORNEAN BRISTLEHEAD'] },
  { Thrasher: ['BROWN THRASHER'] },
  { Wren: ['CACTUS WREN', 'SPLENDID WREN'] },
  { Condor: ['CALIFORNIA CONDOR'] },
  { Gull: ['CALIFORNIA GULL', 'IVORY GULL'] },
  { Quail: ['CALIFORNIA QUAIL', 'GAMBELS QUAIL', 'HARLEQUIN QUAIL'] },
  {
    BeeEater: [
      'RED BEARDED BEE EATER',
      'WHITE THROATED BEE EATER',
      'CARMINE BEE-EATER',
    ],
  },
  { Tern: ['CASPIAN TERN', 'FAIRY TERN', 'INCA TERN'] },
  { Waxwing: ['CEDAR WAXWING'] },
  { Lory: ['DUSKY LORY', 'CHATTERING LORY'] },
  { Nutcracker: ['CLARKS NUTCRACKER'] },
  { Aracari: ['COLLARED ARACARI', 'CURL CRESTED ARACARI'] },
  { Firecrest: ['COMMON FIRECREST'] },
  { Grackle: ['COMMON GRACKLE'] },
  { Iora: ['COMMON IORA'] },
  { Loon: ['COMMON LOON'] },
  { Poorwill: ['COMMON POORWILL'] },
  { Coucal: ['COPPERY TAILED COUCAL'] },
  { Plover: ['CRAB PLOVER', 'GREY PLOVER'] },
  { Caracara: ['CRESTED CARACARA'] },
  { Nuthatch: ['CRESTED NUTHATCH'] },
  { Oropendola: ['CRESTED OROPENDOLA'] },
  { Sunbird: ['CRIMSON SUNBIRD'] },
  { Tody: ['CUBAN TODY'] },
  { Cock: ['COCK OF THE  ROCK'] },
  { Auklet: ['CRESTED AUKLET', 'PARAKETT AUKLET'] },
  { Longclaw: ['CAPE LONGCLAW'] },
  { Coua: ['CRESTED COUA'] },
  { Fireback: ['CRESTED FIREBACK'] },
  { Chat: ['CRIMSON CHAT'] },
  { Crow: ['CROW'] },
  { Trogon: ['CUBAN TROGON', 'ELEGANT TROGON', 'RED NAPED TROGON'] },
  { Parrot: ['DOUBLE EYED FIG PARROT'] },
  { Bluebird: ['EASTERN BLUEBIRD', 'FAIRY BLUEBIRD'] },
  { Weaver: ['EASTERN GOLDEN WEAVER'] },
  { Rosella: ['EASTERN ROSELLA'] },
  { Towee: ['EASTERN TOWEE'] },
  { Penguin: ['EMPEROR PENGUIN', 'FIORDLAND PENGUIN'] },
  { Myna: ['MYNA', 'ENGGANO MYNA'] },
  {
    Dove: [
      'EUROPEAN TURTLE DOVE',
      'MOURNING DOVE',
      'ROCK DOVE',
      'SCARLET CROWNED FRUIT DOVE',
    ],
  },
  { Grosbeak: ['EVENING GROSBEAK'] },
  { Myzornis: ['FIRE TAILLED MYZORNIS'] },
  { Bowerbird: ['FLAME BOWERBIRD', 'REGENT BOWERBIRD'] },
  { Chlorophonia: ['GOLDEN CHLOROPHONIA'] },
  { Ani: ['GROVED BILLED ANI'] },
  { Pitta: ['GURNEYS PITTA', 'INDIAN PITTA', 'RED BELLIED PITTA'] },
  { Bluetail: ['HIMALAYAN BLUETAIL'] },
  { Monal: ['HIMALAYAN MONAL'] },
  { Lark: ['HORNED LARK'] },
  { Macaw: ['HYACINTH MACAW', 'SCARLET MACAW'] },
  { Shaq: ['IMPERIAL SHAQ'] },
  { Canary: ['CANARY'] },
  { Casswary: ['CASSOWARY'] },
  { Emu: ['EMU'] },
  { Flamingo: ['FLAMINGO'] },
  { Frigate: ['FRIGATE'] },
  { GoAwayBird: ['GO AWAY BIRD'] },
  { Falcon: ['GYRFALCON', 'PEREGRINE FALCON'] },
  { Hammerkop: ['HAMMERKOP'] },
  { Vanga: ['HELMET VANGA'] },
  { Merganser: ['HOODED MERGANSER'] },
  { Sungem: ['HORNED SUNGEM'] },
  { Bustard: ['INDIAN BUSTARD'] },
  { Roller: ['INDIAN ROLLER', 'LILAC ROLLER'] },
  {
    Bunting: [
      'LAZULI BUNTING',
      'LARK BUNTING',
      'ORANGE BRESTED BUNTING',
      'PAINTED BUNTING',
      'INDIGO BUNTING',
    ],
  },
  { Dotterel: ['INLAND DOTTEREL'] },
  { Snipe: ['JACK SNIPE'] },
  { Robin: ['JAPANESE ROBIN', 'PINK ROBIN', 'ROBIN'] },
  { Auk: ['LITTLE AUK'] },
  { Stork: ['MARABOU STORK'] },
  { Friarbird: ['NOISY FRIARBIRD'] },
  { Cardinal: ['NORTHERN CARDINAL'] },
  { Mockingbird: ['NORTHERN MOCKINGBIRD'] },
  { Parula: ['NORTHERN PARULA'] },
  { Bishop: ['NORTHERN RED BISHOP'] },
  { Shoveler: ['NORTHERN SHOVELER'] },
  { Rail: ['OKINAWA RAIL'] },
  { TitMouse: ['TIT MOUSE'] },
  { Sandpiper: ['SPOON BILED SANDPIPER'] },
  { Cotinga: ['SPANGLED COTINGA'] },
  { Egret: ['SNOWY EGRET'] },
  { Longspur: ['SMITHS LONGSPUR'] },
  { Dowitcher: ['SHORT BILLED DOWITCHER'] },
  { Buzzard: ['ROUGH LEG BUZZARD'] },
  { Lovebird: ['ROSY FACED LOVEBIRD'] },
  { Bulbul: ['RED WISKERED BULBUL'] },
  { Cormorant: ['RED FACED CORMORANT'] },
  { Lorikeet: ['RAINBOW LORIKEET'] },
  { Swamphen: ['PURPLE SWAMPHEN'] },
  { Gallinule: ['PURPLE GALLINULE'] },
  { Jaeger: ['POMARINE JAEGER'] },
  { Adjutant: ['LESSER ADJUTANT'] },
  { Potoo: ['GREAT POTOO'] },
  { Kiskadee: ['GREAT KISKADEE'] },
  { Jacamar: ['GREAT JACAMAR'] },
  { Bananaquit: ['BANANAQUIT'] },
  { BirdOfParadise: ['BIRD OF PARADISE'] },
  { Bobolink: ['BOBOLINK'] },
  { CharaDeCollar: ['CHARA DE COLLAR'] },
  { Meadowlark: ['EASTERN MEADOWLARK'] },
  { Hoatzin: ['HOATZIN'] },
  { Hoopoes: ['HOOPOES'] },
  { Ibisbill: ['IBISBILL'] },
  { Iwi: ['IWI'] },
  { Jabiru: ['JABIRU'] },
  { Kagu: ['KAGU'] },
  { Kakapo: ['KAKAPO'] },
  { Killdear: ['KILLDEAR'] },
  { Kiwi: ['KIWI'] },
  { Kookaburra: ['KOOKABURRA'] },
  { Malagasy: ['MALAGASY WHITE EYE'] },
  { Maleo: ['MALEO'] },
  { Osprey: ['OSPREY'] },
  { Ostritch: ['OSTRICH'] },
  { Ovenbird: ['OVENBIRD'] },
  { Palila: ['PALILA'] },
  { Peacock: ['PEACOCK'] },
  { Pelican: ['PELICAN'] },
  { Puffin: ['PUFFIN'] },
  { Quetzal: ['QUETZAL'] },
  { Razorbill: ['RAZORBILL'] },
  { Parus: ['PARUS MAJOR'] },
  { Fody: ['RED FODY'] },
  { RoadRunner: ['ROADRUNNER'] },
  { ShoeBill: ['SHOEBILL'] },
  { Sora: ['SORA'] },
  { Spoonbill: ['SPOONBILL'] },
  { Tailorbird: ['TAILORBIRD'] },
  { Takahe: ['TAKAHE'] },
  { Umbrellabird: ['UMBRELLA BIRD'] },
  { Whimbrel: ['WHIMBREL'] },
  { Wilsons: ['WILSONS BIRD OF PARADISE'] },
  { Touchan: ['TOUCHAN'] },
];
